### ISSUE TITLE
Suggestion: Declare ABIs only once for the whole subgraph.yml

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/support#14]
Instead of having to repeatedly define the ABIs for each data source, I think it would be nice to just be able to define them once at the top of the subgraph.yml definition:

```yml
specVersion: 0.0.2
description: Melon protocol
repository: https://github.com/melonproject/melon-subgraph
schema:
  file: ./schema.graphql
abis:
  - name: RegistryContract
    file: ./node_modules/@melonproject/protocol/out/Registry.abi.json
  - name: EngineContract
    file: ./node_modules/@melonproject/protocol/out/Engine.abi.json
  - name: PriceSourceContract
    file: ./node_modules/@melonproject/protocol/out/KyberPriceFeed.abi.json
  - name: RegistryContract
    file: ./node_modules/@melonproject/protocol/out/Registry.abi.json
  - name: VersionContract
    file: ./node_modules/@melonproject/protocol/out/Version.abi.json
  - name: HubContract
    file: ./node_modules/@melonproject/protocol/out/Hub.abi.json
  - name: AccountingContract
    file: ./node_modules/@melonproject/protocol/out/Accounting.abi.json
dataSources:
  - name: RegistryDataSource
    kind: ethereum/contract
    network: mainnet
    source:
      address: '0x1Bfd21f7db126a5966d2C09492676807a68859Ba'
      abi: RegistryContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.2
      language: wasm/assemblyscript
      file: ./src/mappings/Registry.ts
      entities:
        - Asset
        - Version
        - Registry
      eventHandlers:
        - event: VersionRegistration(address)
          handler: handleVersionRegistration
        - event: AssetUpsert(address,string,string,uint256,string,uint256,uint256[],bytes4[])
          handler: handleAssetUpsert
        - event: AssetRemoval(address)
          handler: handleAssetRemoval
        - event: EngineChange(address)
          handler: handleEngineChange
  
  - name: EngineDataSource
    kind: ethereum/contract
    network: mainnet
    source:
      address: '0x7CaEc96607c5c7190d63B5A650E7CE34472352f5'
      abi: EngineContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.2
      language: wasm/assemblyscript
      file: ./src/mappings/Engine.ts
      entities:
        - Engine
        - Registry
      eventHandlers:
        - event: SetAmguPrice(uint256)
          handler: handleSetAmguPrice
        - event: RegistryChange(address)
          handler: handleRegistryChange
        - event: AmguPaid(uint256)
          handler: handleAmguPaid
        - event: Thaw(uint256)
          handler: handleThaw
        - event: Burn(uint256)
          handler: handleBurn

  - name: PriceSourceDataSource
    kind: ethereum/contract
    network: mainnet
    source:
      address: '0x4559DDD9E0a567bD8AB071ac106C1bC2d0C0b6Ef'
      abi: PriceSourceContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.2
      language: wasm/assemblyscript
      file: ./src/mappings/PriceSource.ts
      entities:
        - State
        - Asset
        - AssetPriceUpdate
        - Fund
        - FundCalculationsUpdate
      eventHandlers:
        - event: PriceUpdate(address[],uint256[])
          handler: handlePriceUpdate
```

In addition to that, if one has a directory with all the ABIs in the same place, it could be super handy to just define a file name pattern once?

```yml
specVersion: 0.0.2
description: Melon protocol
repository: https://github.com/melonproject/melon-subgraph
schema:
  file: ./schema.graphql
abis:
  - pattern: ./node_modules/@melonproject/protocol/out/{{name}}.abi.json
dataSources:
  ...
```
