### ISSUE TITLE
Feature request: add event name to EthereumEvent class

### ISSUE THREAD

**Issue by iherger** [graphprotocol/support#53]
For general event logging purposes, it would be very useful to have access to the event name in the `EthereumEvent` class. 

E.g. if my subgraph manifest contains
```yaml
eventHandlers:
  - event: PriceUpdate(address[],uint256[])
    handler: handlePriceUpdate
```
I would like to be able to do something like
```ts
export function handlePriceUpdate(event: PriceUpdate): void {
  saveEvent(event);
  // other code
}
```
My current solution also works, but is more manual and therefore error prone:
```ts
export function handlePriceUpdate(event: PriceUpdate): void {
  saveEvent("PriceUpdate", event);
  // other code
}
```
