### ISSUE TITLE
Contract creation handler

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/support#8]
We currently allow
```yaml
callHandlers:
  - function: constructor(...)
    handler: handleConstructor
```
but it's broken — the constructor handler never gets called.

There's two things we could do:

1. Either map `constructor` function to a trace filter that matches the constructor or disallow `constructor` in `callHandlers`.

2. Add a dedicated `creationHandler` for handling contract creation. Not sure yet how we would detect this but I'm sure there is a way. Ideally, the handler would receive an `EthereumCall` type with the `constructor` arguments as the inputs.
